services:
  cars_service_postgres:
    image: postgres:16.3-alpine
    container_name: cars_service_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cars

  cars_pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: cars_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
